tasks:
  - source: tasks.raw.get_raw_deceases_data
    name: get-raw-deceases-data
    product:
      1991-2000: _products/raw/deceases-1991-2000.parquet
      2001-2014: _products/raw/deceases-2001-2014.parquet
      2015-2017: _products/raw/deceases-2015-2017.parquet

  - source: tasks.clean.get_clean_deceases_data
    name: get-clean-deceases-data
    params:
      cause_specific_codes: "{{causes_codes}}"
      age_group_mapping: "{{age_groups}}"
    product: _products/clean/cleaned-deceases-data.parquet
 
  
  # #########################
  # Rates
  # #########################
  - source: tasks/rates/get-rates.py
    product:
      nb: _products/rates/get-rates.ipynb
      data: _products/rates/rates.csv

  - source: tasks/rates/get-rates-departamental.py
    product:
      nb: _products/rates/get-departamental-rates.ipynb
      data: _products/rates/departamental-rates.csv

  - source: tasks/rates-processing/get-presentation-departmental-csmr.py
    name: get-presentation-departmental-csmr
    product:
      nb: _products/rates-processing/get-presentation-departmental-csmr.ipynb
      data: _products/rates-processing/presentation-departmental-csmr.csv

