tasks:

  # raw
  - source: tasks.raw.get_raw_deceases_data.get_raw_deceases_data
    name: get-raw-deceases-data
    product: 
      data_1991_2000: _products/raw/data-deceases-1991-2000.parquet
      data_2001_2014: _products/raw/data-deceases-2001-2014.parquet
      data_2015_2017: _products/raw/data-deceases-2015-2017.parquet

  # clean
  - source: tasks.clean.get_clean_deceases_data.get_clean_deceases_data
    name: get-clean-deceases-data
    params:
      cause_specific_codes: "{{causes_codes}}"
      age_group_mapping: "{{age_groups}}"
    product: _products/clean/cleaned-deceases-data.parquet
 
  - source: tasks/clean/get-departamental-deceases-tidy-df.py
    name: get-departamental-deceases-tidy-df
    product:
      nb: _products/clean/departamental-deceases-tidy-df.ipynb
      data: _products/clean/departamental-deceases-tidy-df.parquet
  
  # rates
  - source: tasks/rates/get-rates.py
    product:
      nb: _products/rates/get-rates.ipynb
      data: _products/rates/rates.csv

  - source: tasks/rates/get-departamental-csmr.py
    product:
      nb: _products/rates/get-departamental-csmr.ipynb
      data: _products/rates/departamental-csmr.csv

  - source: tasks/rates-processing/merge-and-rename-departmental-csmr.py
    name: merge-and-rename-departmental-csmr
    product:
      nb: _products/rates-processing/merge-and-rename-departmental-csmr.ipynb
      data: _products/rates-processing/departmental-csmr-merged-and-renamed.csv

  # rates-vis
  - source: tasks/rates-vis/departmental/plot-choropleths-with-departmental-rates-by-sex-1997-2017.py
    name: plot-choropleths-with-departmental-rates-by-sex-1997-2017
    product:
      nb: _products/rates-vis/departmental/plot-choropleths-with-departmental-rates-by-sex-1997-2017.ipynb
      img: _products/rates-vis/departmental/choropleths-with-departmental-rates-by-sex-1997-2017.png

  - source: tasks/rates-vis/departmental/plot-choropleths-with-departmental-rates-by-sex-1997-2017-shared-colormap.py
    name: plot-choropleths-with-departmental-rates-by-sex-1997-2017-shared-colormap
    product:
      nb: _products/rates-vis/departmental/plot-choropleths-with-departmental-rates-by-sex-1997-2017-shared-colormap.ipynb
      img: _products/rates-vis/departmental/choropleths-with-departmental-rates-by-sex-1997-2017-shared-colormap.png
