tasks:
  - source: tasks.raw.get_raw_deceases_data
    name: get-raw-deceases-data
    product:
      1991-2000: _products/raw/deceases-1991-2000.parquet
      2001-2014: _products/raw/deceases-2001-2014.parquet
      2015-2017: _products/raw/deceases-2015-2017.parquet

  - source: tasks.clean.get_clean_deceases_data
    name: get-clean-deceases-data
    params:
      age_group_mapping: "{{age_groups}}"
    product: _products/clean/cleaned-deceases-data.parquet

  - source: tasks.filter.get_cause_specific_deceases_data
    name: get-cause-specific-deceases-data
    params:
      causeCodes: "{{causes_codes}}"
    product: _products/filter/get-cause-specific-deceases-data.parquet

  - source: tasks.population.get_clean_population_province_age_group
    name: get-clean-population-province-age-group
    product: _products/population/population-province-age-group.parquet

  # Resultados: Tabla 1
  - source: tasks.generic.mortality.get_csmr_for_divisions
    name: get-csmr-for-divisions
    product:
      csv: _products/generic/cause-specific-rate-for-divisions.csv
      latex: _products/generic/cause-specific-rate-for-divisions.tex

  # #########################
  # Departamental
  # #########################
  - source: tasks.departmental.annual.mortality.get_csmr_by_year
    name: get-departmental-csmr-by-year
    product: _products/departmental/mortality/annual/csmr-by-year.parquet

  - source: tasks.departmental.periodical.mortality.get_csmr_by_periods
    name: get-departmental-csmr-by-periods
    params:
      bins_values: [1990, 1996, 2003, 2010, 2017]
      bins_labels: ['1990-1996', '1997-2003', '2004-2010', '2011-2017']
    product: _products/departmental/mortality/periods/csmr-by-periods.parquet

  - source: tasks.departmental.periodical.mortality_vis.get_csmr_choropleths_by_periods
    name: get-csmr-choropleths-by-periods
    product: _products/departmental/mortality/periods/vis-choropleths

  - source: tasks.departmental.periodical.mortality_vis.get_csmr_moran_clustermaps
    name: get-csmr-moran-clustermap-by-period
    product: _products/departmental/mortality/periods/vis-moran-clustermaps

  # #########################
  # Provincial
  # #########################
  - source: tasks.provincial.mortality.get_csmr_by_year
    name: get-provincial-csmr-by-year
    product: _products/provincial/csmr-by-year.parquet

  # #########################
  # National
  # #########################
  - source: tasks.national.annual.mortality.get_national_csmr
    name: get-national-csmr-by-year
    product: _products/national/mortality/annual/csmr.csv

  # Resultados: Tabla 2
  - source: tasks.national.entire_period.mortality.get_csmr_by_age_group_and_sex
    name: national-entire-period-get-csmr-by-age-group-and-sex
    params:
      age_group_mapping: "{{age_groups}}"
    product: _products/national/mortality/entire-period/csmr-by-age-group-and-sex.csv
