tasks:
  - source: tasks.raw.get_raw_deceases_data
    name: get-raw-deceases-data
    product:
      1991-2000: _products/raw/deceases-1991-2000.parquet
      2001-2014: _products/raw/deceases-2001-2014.parquet
      2015-2017: _products/raw/deceases-2015-2017.parquet

  - source: tasks.clean.get_clean_deceases_data
    name: get-clean-deceases-data
    params:
      age_group_mapping: "{{age_groups}}"
    product: _products/clean/cleaned-deceases-data.parquet

  #- source: tasks.clean.profile_cleaned_deceases_data
  #  name: profile-cleaned-deceases-data
  #  product: _products/clean/profile-deceases-data.html

  - source: tasks.filter.get_cause_specific_deceases_data
    name: get-cause-specific-deceases-data
    params:
      causeCodes: "{{causes_codes}}"
    product: _products/filter/get-cause-specific-deceases-data.parquet

  - source: tasks.population.get_clean_population_province_age_group
    name: get-clean-population-province-age-group
    product: _products/population/population-province-age-group.parquet

  # Resultados: Tabla 1
  - source: tasks.general.mortality.get_csmr_for_divisions
    name: get-csmr-for-divisions
    product: _products/general/cause-specific-rate-for-divisions.parquet

  # Resultados: Tabla 2
  - source: tasks.national.entire_period.mortality.get_csmr_by_age_group_and_sex
    name: national-entire-period-get-csmr-by-age-group-and-sex
    params:
      age_group_mapping: "{{age_groups}}"
    product: _products/national/entire-period/cause-specific-rate-by-age-group-and-sex.parquet

  # Departamental
  - source: tasks.departmental.mortality.get_csmr_by_period
    name: get-departmental-csmr-by-period
    product: _products/departmental/csmr-by-period.parquet

  - source: tasks.departmental.visualizations.get_csmr_clustermaps
    name: get-csmr-clustermaps-by-period
    product: _products/departmental/visualizations/clustermaps

  - source: tasks.departmental.analysis.get_csmr_moran_clustermaps
    name: get-csmr-moran-clustermap-by-period
    product: _products/departmental/analysis/moran-clustermaps
